# Generated by Django 6.0.3 on 2026-06-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionlog',
            name='confidence',
        ),
    ]
