# Generated by Django 6.0.3 on 2026-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_remove_predictionlog_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='is_organic',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='label',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Recyclable', 'Recyclable'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
